version: '0.0.2'
source: "https://github.com/tr7zw/ModComposeTemplate/tree/1.20.2"
replacements:
  group: "dev.tr7zw"
  name: "NotEnoughAnimations"
  id: "notenoughanimations"
  version: "1.6.4"
  author: "tr7zw"
  relocationpackage: "dev.tr7zw.notenoughanimations"
  dependencies: '
  inc project(":NEAVersionless")
  '
  licensename: "LICENSE"
  modrinthid: MPCX6s5C
  curseforgeid: 433760
enabledFlags:
  - autopublish
  - publishFabric
  - publishForge
  - modrinth
  - curseforge
  - versionless
rootProject:
  template: "."
subProjects:
  NEAFabric:
    template: "Fabric"
  NEAForge:
    template: "Forge"
  NEAVersionless:
    template: "Versionless"
    replacements:
      dependencies: '
      compileOnly "com.google.code.gson:gson:2.10.1"

      compileOnly "org.apache.logging.log4j:log4j-core:2.20.0"
      '